export enum ErrorCode {
  NotAuthority = 20001,
  CreateTaskError,
  CancelTaskError,
  ConfigTaskError,
  ListTaskError,
  MarkTaskError,
  GetRewardError,
  EventStreamkError,
  DacNameCheckError,
  DacBindError,
  DacNeedCommunityError,
  DacCreateError,
  DacParamCheckError,
  DacProfileUpdateError,
  DacMemberError,
  DacProfileError,
  DacListInfoError,
  DacAuthorityError,
  DacSymbolNameError,
  DacConfigError,
  DacStateError,
  DacDacsError,
  DacFindByChannelError,
  DacNotFound,
  DacMyVoteError,
  DacShowProposalError,
}
